server:
  port: 9192

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohd-zaid78/microservices-projects
          default-label: main
          clone-on-start: true
          
